# Generated by Django 5.2.14 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(choices=[("text", "Tekstowy"), ("voice", "Glosowy")], default="text", max_length=10),
        ),
    ]
